import { useEffect, useState } from "react";
import { Account, api } from "./lib/api";

export function AdminPortal({ admin }: { admin: Account }) {
  const [users, setUsers] = useState<Account[]>([]); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const reload = async () => { setLoading(true); try { setUsers((await api.adminUsers()).users); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر تحميل المستخدمين."); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  const update = async (user: Account, patch: Partial<Account>) => { try { const result = await api.updateUser(user.id, patch); setUsers(users.map(item => item.id === user.id ? result.user : item)); setNotice("تم تحديث حساب المستخدم."); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر التحديث."); } };
  const logout = async () => { await api.logout(); location.assign("/admin"); };
  return <div className="shell"><aside><div className="identity"><span className="brand-mark">A</span><div><strong>{admin.username}</strong><small>إدارة النظام</small></div></div><nav><button className="nav-active">المستخدمون والصلاحيات</button></nav><div className="connection"><b>مدير النظام</b><span>الموافقة والتفعيل والتجديد</span></div></aside><main className="content">{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}<header className="page-head"><div><p className="eyebrow">بوابة إدارة منفصلة</p><h1>المستخدمون والتفعيل</h1><p>اعتماد الحسابات، تعليقها، ضبط دورها، وتحديد تاريخ انتهاء التفعيل. لا يمكن للمستخدم الدخول ما لم تكن حالته نشطة.</p></div><button className="secondary" onClick={() => void logout()}>تسجيل الخروج</button></header><section className="panel"><h2>كل المستخدمين</h2>{loading ? <p>جارٍ التحميل…</p> : <div className="admin-table">{users.map(user => <article className="admin-row" key={user.id}><div><b dir="ltr">{user.username}</b><small>أنشئ: {new Date(user.createdAt).toLocaleDateString("ar")}</small></div><label>الدور<select value={user.role} onChange={event => void update(user, { role: event.target.value as Account["role"] })}><option value="user">مستخدم</option><option value="admin">مدير</option></select></label><label>الحالة<select value={user.status} onChange={event => void update(user, { status: event.target.value as Account["status"] })}><option value="pending">قيد المراجعة</option><option value="active">نشط</option><option value="suspended">موقوف</option><option value="expired">منتهٍ</option></select></label><label>انتهاء التفعيل<input dir="ltr" type="datetime-local" value={user.activationExpiresAt ? new Date(user.activationExpiresAt).toISOString().slice(0, 16) : ""} onChange={event => void update(user, { activationExpiresAt: event.target.value ? new Date(event.target.value).toISOString() : null })} /></label></article>)}</div>}</section></main></div>;
}
