import { useEffect, useMemo, useState } from "react";
import { buildRsc, generateCards } from "./lib/cardEngine";
import { defaultGenerator, type AppData, type Batch, type Device, type Plan, type PrintTemplate } from "./lib/model";
import { exportBatchPdf } from "./lib/pdf";
import { SecureStore } from "./lib/secureStore";
import "./styles.css";

type View = "batches" | "create" | "plans" | "devices" | "templates";
type Runtime = { platform: "desktop" | "android"; sendBatch: (input: { host: string; port: number; username: string; password: string; script: string; scriptName: string }) => Promise<{ scriptName: string; status: "sent" }> };
const id = () => crypto.randomUUID();
const downloadText = (content: string, filename: string) => { const url = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); };

function LockScreen({ onUnlock }: { onUnlock: (pin: string) => Promise<void> }) {
  const [pin, setPin] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const unlock = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await onUnlock(pin); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر فتح التطبيق."); } finally { setBusy(false); } };
  return <main className="lock-screen"><form onSubmit={unlock} className="lock-card"><span className="brand-mark">M</span><h1>مدير كروت MikroTik</h1><p>تُحفظ البيانات على هذا الجهاز فقط في قاعدة محلية مشفرة. لا يلزم اتصال إنترنت لإنشاء الكروت أو الطباعة والتصدير.</p><label>رمز قفل محلي (6 رموز فأكثر)<input type="password" inputMode="numeric" minLength={6} required value={pin} onChange={event => setPin(event.target.value)} autoFocus /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? "جارٍ فتح القفل…" : "فتح التطبيق"}</button><small>في أول استخدام ينشئ هذا الرمز خزنة محلية جديدة.</small></form></main>;
}

function App() {
  const store = useMemo(() => new SecureStore(), []);
  const [data, setData] = useState<AppData | null>(null);
  const [view, setView] = useState<View>("batches");
  const [notice, setNotice] = useState("");
  const [runtime, setRuntime] = useState<Runtime | null>(null);
  useEffect(() => {
    const desktop = window.cardManagerRuntime;
    if (desktop) { desktop.capabilities().then(() => setRuntime({ platform: "desktop", sendBatch: desktop.sendBatch })).catch(() => undefined); return; }
    const android = window.Capacitor?.Plugins?.MikroTikTransport;
    if (android) setRuntime({ platform: "android", sendBatch: android.sendBatch });
  }, []);
  const unlock = async (pin: string) => setData(await store.unlock(pin));
  const persist = async (next: AppData) => { await store.save(next); setData(next); };
  if (!data) return <LockScreen onUnlock={unlock} />;
  const deviceMap = new Map(data.devices.map(device => [device.id, device]));
  const planMap = new Map(data.plans.map(plan => [plan.id, plan]));
  const templateMap = new Map(data.templates.map(template => [template.id, template]));
  const addDevice = async (device: Device) => persist({ ...data, devices: [...data.devices, device] });
  const addPlan = async (plan: Plan) => persist({ ...data, plans: [...data.plans, plan] });
  const saveTemplate = async (template: PrintTemplate) => persist({ ...data, templates: data.templates.some(item => item.id === template.id) ? data.templates.map(item => item.id === template.id ? template : item) : [...data.templates, template] });
  const addBatch = async (batch: Batch) => persist({ ...data, batches: [batch, ...data.batches], nextSerial: data.nextSerial + batch.cards.length });
  const deleteBatch = async (batchId: string) => persist({ ...data, batches: data.batches.filter(batch => batch.id !== batchId) });
  const cancelBatch = async (batchId: string) => persist({ ...data, batches: data.batches.map(batch => batch.id === batchId ? { ...batch, status: "cancelled" } : batch) });
  const markSent = async (batchId: string) => persist({ ...data, batches: data.batches.map(batch => batch.id === batchId ? { ...batch, status: "sent" } : batch) });
  return <div className="shell"><aside><div className="identity"><span className="brand-mark">M</span><div><strong>مدير الكروت</strong><small>وضع محلي مستقل</small></div></div><nav>{([ ["batches", "الدفعات"], ["create", "إنشاء دفعة"], ["plans", "الباقات"], ["templates", "قوالب الطباعة"], ["devices", "أجهزة MikroTik"] ] as Array<[View, string]>).map(([key, label]) => <button className={view === key ? "nav-active" : ""} key={key} onClick={() => setView(key)}>{label}</button>)}</nav><div className="connection"><b>{runtime ? runtime.platform === "android" ? "تطبيق Android" : "تطبيق سطح المكتب" : "PWA دون إنترنت"}</b><span>{runtime ? "اتصال API يدوي متاح" : "طباعة وتصدير محليان"}</span></div><button className="lock" onClick={() => { store.lock(); setData(null); }}>قفل التطبيق</button></aside><main className="content">{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}{view === "batches" && <Batches batches={data.batches} deviceMap={deviceMap} planMap={planMap} templateMap={templateMap} runtime={runtime} onDelete={deleteBatch} onCancel={cancelBatch} onSend={markSent} onNotice={setNotice} />}{view === "create" && <CreateBatch data={data} onAdd={addBatch} onDone={() => setView("batches")} onNotice={setNotice} />}{view === "plans" && <Plans plans={data.plans} onAdd={addPlan} />}{view === "devices" && <Devices devices={data.devices} onAdd={addDevice} />}{view === "templates" && <Templates templates={data.templates} onSave={saveTemplate} />}</main></div>;
}

function Header({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <header className="page-head"><div><p className="eyebrow">تشغيل دون شبكة</p><h1>{title}</h1><p>{text}</p></div>{action}</header>; }

function Devices({ devices, onAdd }: { devices: Device[]; onAdd: (device: Device) => Promise<void> }) { const [form, setForm] = useState({ name: "", host: "", version: "7" as "6" | "7", username: "admin", password: "", apiPort: 8728, restPort: 443 }); const submit = async (event: React.FormEvent) => { event.preventDefault(); await onAdd({ id: id(), ...form }); setForm({ name: "", host: "", version: "7", username: "admin", password: "", apiPort: 8728, restPort: 443 }); }; return <><Header title="أجهزة MikroTik" text="تُخزن بيانات الجهاز مشفرة على هذا الجهاز. لا يبدأ أي اتصال عند الحفظ." /><section className="two-column"><form className="panel form-grid" onSubmit={submit}><h2>إضافة جهاز</h2><label>اسم الجهاز<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>IP أو النطاق<input dir="ltr" required value={form.host} onChange={event => setForm({ ...form, host: event.target.value })} placeholder="192.168.88.1" /></label><label>الإصدار<select value={form.version} onChange={event => setForm({ ...form, version: event.target.value as "6" | "7" })}><option value="7">RouterOS 7</option><option value="6">RouterOS 6</option></select></label><label>اسم مستخدم API<input dir="ltr" required value={form.username} onChange={event => setForm({ ...form, username: event.target.value })} /></label><label>كلمة المرور<input dir="ltr" type="password" required value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><label>منفذ API<input dir="ltr" type="number" value={form.apiPort} onChange={event => setForm({ ...form, apiPort: Number(event.target.value) })} /></label><label>منفذ REST<input dir="ltr" type="number" value={form.restPort} onChange={event => setForm({ ...form, restPort: Number(event.target.value) })} /></label><p className="hint">الإرسال اليدوي في APK يستخدم API غير المشفر على المنفذ 8728 داخل الشبكة المحلية. لا يبدأ الاتصال عند الحفظ.</p><button>حفظ محلي</button></form><section className="panel"><h2>الأجهزة المحفوظة</h2>{devices.length ? <ul className="list">{devices.map(device => <li key={device.id}><b>{device.name}</b><span dir="ltr">{device.host}</span><small>RouterOS {device.version} · API {device.apiPort}</small></li>)}</ul> : <Empty text="لا توجد أجهزة محفوظة. يمكنك متابعة التوليد والطباعة دون جهاز." />}</section></section></> }

function Plans({ plans, onAdd }: { plans: Plan[]; onAdd: (plan: Plan) => Promise<void> }) { const [name, setName] = useState(""); const [profile, setProfile] = useState(""); const [accessMode, setAccessMode] = useState<"hotspot" | "user_manager">("hotspot"); const submit = async (event: React.FormEvent) => { event.preventDefault(); await onAdd({ id: id(), name, profileName: profile, accessMode, generator: structuredClone(defaultGenerator) }); setName(""); setProfile(""); }; return <><Header title="الباقات" text="تحدد الباقة نوع حساب MikroTik وProfile وقواعد التوليد الافتراضية." /><section className="two-column"><form className="panel form-grid" onSubmit={submit}><h2>إضافة باقة</h2><label>اسم الباقة<input required value={name} onChange={event => setName(event.target.value)} /></label><label>النوع<select value={accessMode} onChange={event => setAccessMode(event.target.value as "hotspot" | "user_manager")}><option value="hotspot">Hotspot</option><option value="user_manager">User Manager</option></select></label><label>اسم Profile<input dir="ltr" value={profile} onChange={event => setProfile(event.target.value)} /></label><button>حفظ الباقة</button></form><section className="panel"><h2>الباقات المحفوظة</h2>{plans.length ? <ul className="list">{plans.map(plan => <li key={plan.id}><b>{plan.name}</b><span>{plan.accessMode === "hotspot" ? "Hotspot" : "User Manager"}</span><small dir="ltr">{plan.profileName || "بدون Profile"}</small></li>)}</ul> : <Empty text="أضف باقة محلية أو استوردها من نسخة سطح المكتب عند اتصالك بالراوتر." />}</section></section></> }

function Templates({ templates, onSave }: { templates: PrintTemplate[]; onSave: (template: PrintTemplate) => Promise<void> }) { const [selected, setSelected] = useState(templates[0]); useEffect(() => { if (!templates.some(item => item.id === selected.id)) setSelected(templates[0]); }, [templates, selected]); const set = (key: "rows" | "columns", value: number) => setSelected({ ...selected, [key]: Math.max(1, Math.min(key === "rows" ? 30 : 12, value)) }); const file = (event: React.ChangeEvent<HTMLInputElement>) => { const image = event.target.files?.[0]; if (!image || image.size > 5 * 1024 * 1024) return; const reader = new FileReader(); reader.onload = () => setSelected({ ...selected, backgroundDataUrl: String(reader.result) }); reader.readAsDataURL(image); }; const cardCount = selected.rows * selected.columns; return <><Header title="قوالب الطباعة" text="تتمدد الخلفية مستقلة داخل كل بطاقة؛ يستعمل PDF الإحداثيات والملليمترات نفسها." action={<button onClick={() => onSave(selected)}>حفظ القالب</button>} /><section className="template-layout"><div className="panel form-grid"><label>اسم القالب<input value={selected.name} onChange={event => setSelected({ ...selected, name: event.target.value })} /></label><label>الصفوف<input type="number" min="1" max="30" value={selected.rows} onChange={event => set("rows", Number(event.target.value))} /></label><label>الأعمدة<input type="number" min="1" max="12" value={selected.columns} onChange={event => set("columns", Number(event.target.value))} /></label><label>خلفية الكرت<input type="file" accept="image/png,image/jpeg" onChange={file} /></label><p className="hint">{cardCount} بطاقة لكل A4. للخلفية ملء كامل داخل كل بطاقة، وليست صورة واحدة مقطعة عبر الصفحة.</p></div><div className="paper-wrap"><div className="paper" style={{ gridTemplateColumns: `repeat(${selected.columns}, 1fr)`, gridTemplateRows: `repeat(${selected.rows}, 1fr)`, gap: `${selected.gaps.y}mm ${selected.gaps.x}mm`, padding: `${selected.margins.top}mm ${selected.margins.right}mm ${selected.margins.bottom}mm ${selected.margins.left}mm` }}>{Array.from({ length: cardCount }, (_, index) => <div key={index} className="card-preview" style={{ backgroundImage: selected.backgroundDataUrl ? `url(${selected.backgroundDataUrl})` : undefined }}><b dir="ltr">481925</b><span dir="ltr">481925</span></div>)}</div></div></section></> }

function CreateBatch({ data, onAdd, onDone, onNotice }: { data: AppData; onAdd: (batch: Batch) => Promise<void>; onDone: () => void; onNotice: (value: string) => void }) { const [planId, setPlanId] = useState(data.plans[0]?.id ?? ""); const [deviceId, setDeviceId] = useState(""); const [templateId, setTemplateId] = useState(data.templates[0]?.id ?? "default"); const [count, setCount] = useState(20); const [version, setVersion] = useState<"6" | "7">("7"); const create = async (event: React.FormEvent) => { event.preventDefault(); const plan = data.plans.find(item => item.id === planId); if (!plan) return onNotice("اختر باقة أولاً."); const device = data.devices.find(item => item.id === deviceId); const cards = generateCards(count, data.nextSerial, plan.generator, data.batches.flatMap(batch => batch.cards.map(card => card.username))); const routerVersion = device?.version ?? version; const batch: Batch = { id: id(), createdAt: new Date().toISOString(), planId: plan.id, deviceId: device?.id, templateId, routerVersion, cards, script: buildRsc(cards, plan.accessMode, routerVersion, plan.profileName), status: "local" }; await onAdd(batch); onNotice("حُفظت الدفعة محلياً مع PDF وRSC. لا يُرسل أي شيء إلى الراوتر تلقائياً."); onDone(); }; return <><Header title="إنشاء دفعة" text="أنشئ واطبع وصدّر بلا اتصال. اختيار جهاز لا يعني الإرسال؛ الإرسال خطوة منفصلة لاحقة." /><form className="panel create-form" onSubmit={create}><label>الباقة<select required value={planId} onChange={event => setPlanId(event.target.value)}><option value="">اختر باقة</option>{data.plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label>الجهاز <small>(اختياري)</small><select value={deviceId} onChange={event => setDeviceId(event.target.value)}><option value="">دون جهاز — طباعة وتنزيل فقط</option>{data.devices.map(device => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label>{!deviceId && <label>إصدار RSC<select value={version} onChange={event => setVersion(event.target.value as "6" | "7")}><option value="7">RouterOS 7</option><option value="6">RouterOS 6</option></select></label>}<label>قالب الطباعة<select value={templateId} onChange={event => setTemplateId(event.target.value)}>{data.templates.map(template => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label>عدد الكروت<input dir="ltr" type="number" min="1" max="2000" value={count} onChange={event => setCount(Number(event.target.value))} /></label><button disabled={!planId}>حفظ الدفعة محلياً</button></form></> }

function Batches({ batches, deviceMap, planMap, templateMap, runtime, onDelete, onCancel, onSend, onNotice }: { batches: Batch[]; deviceMap: Map<string, Device>; planMap: Map<string, Plan>; templateMap: Map<string, PrintTemplate>; runtime: Runtime | null; onDelete: (id: string) => Promise<void>; onCancel: (id: string) => Promise<void>; onSend: (id: string) => Promise<void>; onNotice: (value: string) => void }) { const pdf = async (batch: Batch) => { const template = templateMap.get(batch.templateId ?? "") ?? templateMap.get("default"); if (template) await exportBatchPdf(batch, template); }; const send = async (batch: Batch) => { const device = batch.deviceId ? deviceMap.get(batch.deviceId) : undefined; if (!runtime || !device) return onNotice("اختر جهازاً للدفعة وافتحها في نسخة سطح المكتب أو APK قبل الإرسال."); if (!confirm("سيُحفظ سكربت واحد للدفعة على MikroTik ثم يُشغّل مرة واحدة. هل تؤكد الإرسال؟")) return; try { const result = await runtime.sendBatch({ host: device.host, port: device.apiPort, username: device.username, password: device.password, script: batch.script, scriptName: `card_batch_${batch.id.replace(/-/g, "").slice(0, 20)}` }); await onSend(batch.id); onNotice(`تم تشغيل سكربت الدفعة مرة واحدة باسم ${result.scriptName}.`); } catch (error) { onNotice(error instanceof Error ? error.message : "تعذر تنفيذ سكربت الدفعة."); } }; return <><Header title="دفعات الكروت" text="كل دفعة محلية حتى تضغط إرسالاً يدوياً. يمكنك حذفها أو إلغاؤها أو طباعتها دون أي اتصال بالراوتر." />{batches.length ? <div className="batch-grid">{batches.map(batch => <article className="batch" key={batch.id}><div><span className={`status ${batch.status}`}>{batch.status === "local" ? "محلية — لم تُرسل" : batch.status === "cancelled" ? "أُلغي الإرسال" : "تم الإرسال"}</span><h2>{planMap.get(batch.planId)?.name ?? "باقة محذوفة"}</h2><p>{batch.cards.length} كرت · {batch.routerVersion === "7" ? "RouterOS 7" : "RouterOS 6"} · {deviceMap.get(batch.deviceId ?? "")?.name ?? "دون جهاز"}</p></div><div className="batch-actions"><button onClick={() => void pdf(batch)}>تنزيل PDF</button><button className="secondary" onClick={() => downloadText(batch.script, `mikrotik-${batch.id}.rsc`)}>تنزيل RSC</button><button className="secondary" onClick={() => downloadText(batch.cards.map(card => `${card.serial}\t${card.username}`).join("\n"), `cards-${batch.id}.txt`)}>تنزيل TXT</button>{batch.status === "local" && <button className="secondary" onClick={() => void onCancel(batch.id)}>إلغاء الإرسال</button>}<button className="danger" onClick={() => { if (confirm("حذف الدفعة المحلية نهائياً؟")) void onDelete(batch.id); }}>حذف</button><button disabled={!runtime || !batch.deviceId || batch.status !== "local"} title={runtime ? "إرسال يدوي فقط بعد التأكيد" : "يتطلب الإرسال نسخة سطح المكتب أو APK"} onClick={() => void send(batch)}>إرسال الدفعة إلى MikroTik</button></div></article>)}</div> : <Empty text="لا توجد دفعات. يمكنك إنشاء دفعة محلية وطباعتها أو تنزيلها دون جهاز أو إنترنت." />}</> }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }

export default App;
