import { FormEvent, useEffect, useState } from "react";
import { api, Account } from "./lib/api";
import { buildRsc, generateCards } from "./lib/cardEngine";
import { defaultGenerator, GeneratorSettings } from "./lib/model";

type RecordValue = { id: string; [key: string]: unknown };
type View = "devices" | "plans" | "templates" | "batches";
const tabs: Array<[View, string]> = [["devices", "الأجهزة"], ["plans", "الباقات"], ["templates", "القوالب"], ["batches", "الدفعات"]];

function Header({ title, text, onLogout }: { title: string; text: string; onLogout: () => void }) { return <header className="page-head"><div><p className="eyebrow">مساحة مستخدم خاصة</p><h1>{title}</h1><p>{text}</p></div><button className="secondary" onClick={onLogout}>تسجيل الخروج</button></header>; }

export function UserPortal({ user }: { user: Account }) {
  const [view, setView] = useState<View>("devices");
  const [notice, setNotice] = useState("");
  const logout = async () => { await api.logout(); location.assign("/"); };
  return <div className="shell"><aside><div className="identity"><span className="brand-mark">M</span><div><strong>{user.username}</strong><small>مساحة بيانات خاصة</small></div></div><nav>{tabs.map(([key, label]) => <button className={view === key ? "nav-active" : ""} onClick={() => setView(key)} key={key}>{label}</button>)}</nav><div className="connection"><b>حساب مفعل</b><span>السجلات لا تظهر لمستخدم آخر</span></div></aside><main className="content">{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}{view === "devices" && <Devices onNotice={setNotice} />}{view === "plans" && <Plans onNotice={setNotice} />}{view === "templates" && <Templates onNotice={setNotice} />}{view === "batches" && <Batches onNotice={setNotice} />}<button className="lock" onClick={() => void logout()}>تسجيل الخروج</button></main></div>;
}

function useRecords(kind: string) {
  const [records, setRecords] = useState<RecordValue[]>([]); const [loading, setLoading] = useState(true);
  const reload = async () => { setLoading(true); try { const response = await api.list<RecordValue>(kind); setRecords(response.records); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, [kind]);
  const remove = async (id: string) => { await api.remove(kind, id); await reload(); };
  const create = async (payload: Record<string, unknown>) => { await api.create(kind, payload); await reload(); };
  const update = async (id: string, payload: Record<string, unknown>) => { await api.update(kind, id, payload); await reload(); };
  return { records, loading, reload, remove, create, update };
}

function Devices({ onNotice }: { onNotice: (message: string) => void }) {
  const { records, loading, reload, remove } = useRecords("device");
  const [editing, setEditing] = useState<RecordValue | null>(null);
  const [form, setForm] = useState({ name: "", host: "", apiPort: "8728", restPort: "443", version: "7", username: "admin", password: "" });
  const begin = (record?: RecordValue) => { setEditing(record ?? null); setForm({ name: String(record?.name ?? ""), host: String(record?.host ?? ""), apiPort: String(record?.apiPort ?? "8728"), restPort: String(record?.restPort ?? "443"), version: String(record?.version ?? "7"), username: String(record?.username ?? "admin"), password: String(record?.password ?? "") }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const payload = { ...form, apiPort: Number(form.apiPort), restPort: Number(form.restPort) }; try { if (editing) await api.update("device", editing.id, payload); else await api.create("device", payload); await reload(); begin(); onNotice("تم حفظ الجهاز في مساحتك الخاصة. لا يبدأ الاتصال بالراوتر عند الحفظ."); } catch (error) { onNotice(error instanceof Error ? error.message : "تعذر حفظ الجهاز."); } };
  return <><Header title="أجهزة MikroTik" text="أضف أو عدّل أو احذف الأجهزة الخاصة بحسابك فقط. بيانات الدخول لا تظهر لباقي المستخدمين." onLogout={() => void api.logout().then(() => location.assign("/"))} /><section className="two-column"><form className="panel form-grid" onSubmit={submit}><h2>{editing ? "تعديل جهاز" : "إضافة جهاز"}</h2><label>اسم الجهاز<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>IP أو النطاق<input dir="ltr" required value={form.host} onChange={e => setForm({ ...form, host: e.target.value })} /></label><label>الإصدار<select value={form.version} onChange={e => setForm({ ...form, version: e.target.value })}><option value="6">RouterOS 6</option><option value="7">RouterOS 7</option></select></label><label>منفذ API<input dir="ltr" type="number" value={form.apiPort} onChange={e => setForm({ ...form, apiPort: e.target.value })} /></label><label>اسم المستخدم<input dir="ltr" required value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></label><label>كلمة المرور<input dir="ltr" type="password" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button>{editing ? "حفظ التعديل" : "إضافة الجهاز"}</button>{editing && <button className="secondary" type="button" onClick={() => begin()}>إلغاء</button>}</form><section className="panel"><h2>الأجهزة الخاصة بك</h2>{loading ? <p>جارٍ التحميل…</p> : records.length ? <ul className="list">{records.map(record => <li key={record.id}><b>{String(record.name)}</b><span dir="ltr">{String(record.host)} · API {String(record.apiPort)}</span><div className="batch-actions"><button className="secondary" onClick={() => begin(record)}>تعديل</button><button className="danger" onClick={() => { if (confirm("حذف هذا الجهاز؟")) void remove(record.id).then(() => onNotice("تم حذف الجهاز.")); }}>حذف</button></div></li>)}</ul> : <Empty text="لا توجد أجهزة في حسابك." />}</section></section></>;
}

function Plans({ onNotice }: { onNotice: (message: string) => void }) {
  const { records, loading, reload, remove } = useRecords("plan"); const [editing, setEditing] = useState<RecordValue | null>(null); const [form, setForm] = useState({ name: "", accessMode: "hotspot", profileName: "", duration: "", speed: "", price: "" });
  const begin = (record?: RecordValue) => { setEditing(record ?? null); setForm({ name: String(record?.name ?? ""), accessMode: String(record?.accessMode ?? "hotspot"), profileName: String(record?.profileName ?? ""), duration: String(record?.duration ?? ""), speed: String(record?.speed ?? ""), price: String(record?.price ?? "") }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); try { if (editing) await api.update("plan", editing.id, form); else await api.create("plan", form); await reload(); begin(); onNotice("تم حفظ الباقة."); } catch (error) { onNotice(error instanceof Error ? error.message : "تعذر حفظ الباقة."); } };
  return <><Header title="الباقات" text="كل باقة تابعة لحسابك فقط، ويمكن تعديلها أو حذفها في أي وقت." onLogout={() => void api.logout().then(() => location.assign("/"))} /><section className="two-column"><form className="panel form-grid" onSubmit={submit}><h2>{editing ? "تعديل باقة" : "إضافة باقة"}</h2><label>اسم الباقة<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>النوع<select value={form.accessMode} onChange={e => setForm({ ...form, accessMode: e.target.value })}><option value="hotspot">Hotspot</option><option value="user_manager">User Manager</option></select></label><label>Profile<input dir="ltr" value={form.profileName} onChange={e => setForm({ ...form, profileName: e.target.value })} /></label><label>المدة<input value={form.duration} onChange={e => setForm({ ...form, duration: e.target.value })} placeholder="30 يوم" /></label><label>السرعة<input dir="ltr" value={form.speed} onChange={e => setForm({ ...form, speed: e.target.value })} placeholder="10M/10M" /></label><label>السعر<input dir="ltr" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} /></label><button>{editing ? "حفظ التعديل" : "إضافة الباقة"}</button>{editing && <button className="secondary" type="button" onClick={() => begin()}>إلغاء</button>}</form><section className="panel"><h2>الباقات الخاصة بك</h2>{loading ? <p>جارٍ التحميل…</p> : records.length ? <ul className="list">{records.map(record => <li key={record.id}><b>{String(record.name)}</b><span>{String(record.duration || "")}{record.speed ? ` · ${String(record.speed)}` : ""}{record.price ? ` · ${String(record.price)}` : ""}</span><small dir="ltr">{String(record.profileName || "بدون Profile")}</small><div className="batch-actions"><button className="secondary" onClick={() => begin(record)}>تعديل</button><button className="danger" onClick={() => { if (confirm("حذف هذه الباقة؟")) void remove(record.id).then(() => onNotice("تم حذف الباقة.")); }}>حذف</button></div></li>)}</ul> : <Empty text="لا توجد باقات في حسابك." />}</section></section></>;
}

function Templates({ onNotice }: { onNotice: (message: string) => void }) {
  const { records, loading, reload, remove } = useRecords("template"); const [editing, setEditing] = useState<RecordValue | null>(null); const [form, setForm] = useState({ name: "", rows: "4", columns: "2", margins: "10", gap: "4" });
  const begin = (record?: RecordValue) => { setEditing(record ?? null); setForm({ name: String(record?.name ?? ""), rows: String(record?.rows ?? 4), columns: String(record?.columns ?? 2), margins: String(record?.margins ?? 10), gap: String(record?.gap ?? 4) }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const payload = { ...form, rows: Number(form.rows), columns: Number(form.columns), margins: Number(form.margins), gap: Number(form.gap) }; try { if (editing) await api.update("template", editing.id, payload); else await api.create("template", payload); await reload(); begin(); onNotice("تم حفظ قالب الطباعة. يمكنك تعديل الصفوف والأعمدة في أي وقت."); } catch (error) { onNotice(error instanceof Error ? error.message : "تعذر حفظ القالب."); } };
  return <><Header title="قوالب الطباعة" text="القوالب مملوكة لحسابك وحده ويمكن تعديل إعداداتها أو حذفها دون التأثير على مستخدم آخر." onLogout={() => void api.logout().then(() => location.assign("/"))} /><section className="two-column"><form className="panel form-grid" onSubmit={submit}><h2>{editing ? "تعديل قالب" : "إضافة قالب"}</h2><label>اسم القالب<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>الصفوف<input type="number" min="1" max="30" value={form.rows} onChange={e => setForm({ ...form, rows: e.target.value })} /></label><label>الأعمدة<input type="number" min="1" max="12" value={form.columns} onChange={e => setForm({ ...form, columns: e.target.value })} /></label><label>الهامش (mm)<input type="number" min="0" value={form.margins} onChange={e => setForm({ ...form, margins: e.target.value })} /></label><label>المسافة (mm)<input type="number" min="0" value={form.gap} onChange={e => setForm({ ...form, gap: e.target.value })} /></label><button>{editing ? "حفظ التعديل" : "إضافة القالب"}</button>{editing && <button className="secondary" type="button" onClick={() => begin()}>إلغاء</button>}</form><section className="panel"><h2>القوالب الخاصة بك</h2>{loading ? <p>جارٍ التحميل…</p> : records.length ? <ul className="list">{records.map(record => <li key={record.id}><b>{String(record.name)}</b><span>{String(record.rows)} صفوف × {String(record.columns)} أعمدة</span><small>{String(record.margins)}mm هوامش · {String(record.gap)}mm مسافة</small><div className="batch-actions"><button className="secondary" onClick={() => begin(record)}>تعديل</button><button className="danger" onClick={() => { if (confirm("حذف هذا القالب؟")) void remove(record.id).then(() => onNotice("تم حذف القالب.")); }}>حذف</button></div></li>)}</ul> : <Empty text="لا توجد قوالب في حسابك." />}</section></section></>;
}

function Batches({ onNotice }: { onNotice: (message: string) => void }) {
  const batchState = useRecords("batch"); const planState = useRecords("plan"); const deviceState = useRecords("device");
  const [name, setName] = useState("دفعة جديدة"); const [planId, setPlanId] = useState(""); const [deviceId, setDeviceId] = useState(""); const [count, setCount] = useState("10"); const [mode, setMode] = useState<GeneratorSettings["mode"]>("different"); const [length, setLength] = useState("6");
  const createBatch = async (event: FormEvent) => {
    event.preventDefault(); const plan = planState.records.find(item => item.id === planId); const device = deviceState.records.find(item => item.id === deviceId); if (!plan) return onNotice("اختر باقة قبل إنشاء الدفعة.");
    try {
      const requested = Number(count); const codeLength = Number(length); if (!Number.isInteger(requested) || requested < 1 || requested > 500 || !Number.isInteger(codeLength) || codeLength < 3 || codeLength > 30) return onNotice("تحقق من العدد والطول: العدد من 1 إلى 500 والطول من 3 إلى 30.");
      const generator = { ...defaultGenerator, mode, username: { ...defaultGenerator.username, length: codeLength, letterCase: "mixed" as const }, password: { ...defaultGenerator.password, length: codeLength, letterCase: "mixed" as const } };
      const used = batchState.records.flatMap(record => Array.isArray(record.cards) ? record.cards as Array<{ username?: string }> : []).map(card => card.username ?? "");
      const previousSerial = batchState.records.flatMap(record => Array.isArray(record.cards) ? record.cards as Array<{ serial?: number }> : []).reduce((highest, card) => Math.max(highest, Number(card.serial ?? 0)), 0);
      const cards = generateCards(requested, previousSerial + 1, generator, used); const accessMode = String(plan.accessMode) === "user_manager" ? "user_manager" : "hotspot"; const version = String(device?.version ?? "7") === "6" ? "6" : "7"; const script = buildRsc(cards, accessMode, version, String(plan.profileName ?? ""), "admin");
      await batchState.create({ name, planId: plan.id, deviceId: device?.id, routerVersion: version, accessMode, count: cards.length, cards, script, status: "local", createdAt: new Date().toISOString() }); setName("دفعة جديدة"); onNotice("تم إنشاء الدفعة وحفظ ملف RSC واحد. لم يبدأ أي إرسال تلقائي.");
    } catch (error) { onNotice(error instanceof Error ? error.message : "تعذر إنشاء الدفعة."); }
  };
  const download = (record: RecordValue) => { const link = document.createElement("a"); const url = URL.createObjectURL(new Blob([String(record.script ?? "")], { type: "text/plain;charset=utf-8" })); link.href = url; link.download = `${String(record.name ?? "batch").replace(/[^a-z0-9_-]+/gi, "-")}.rsc`; link.click(); URL.revokeObjectURL(url); };
  return <><Header title="سجل الدفعات" text="أنشئ الدفعة وصدّر سكربت RSC أو ألغها قبل أي إرسال. يبدأ الإرسال يدوياً فقط من تطبيق سطح المكتب أو APK." onLogout={() => void api.logout().then(() => location.assign("/"))} /><section className="two-column"><form className="panel form-grid" onSubmit={createBatch}><h2>إنشاء دفعة</h2><label>اسم الدفعة<input required value={name} onChange={event => setName(event.target.value)} /></label><label>الباقة<select required value={planId} onChange={event => setPlanId(event.target.value)}><option value="">اختر باقة</option>{planState.records.map(plan => <option key={plan.id} value={plan.id}>{String(plan.name)}</option>)}</select></label><label>الجهاز (اختياري)<select value={deviceId} onChange={event => setDeviceId(event.target.value)}><option value="">دون جهاز</option>{deviceState.records.map(device => <option key={device.id} value={device.id}>{String(device.name)}</option>)}</select></label><label>عدد الكروت<input type="number" min="1" max="500" value={count} onChange={event => setCount(event.target.value)} /></label><label>نمط الحساب<select value={mode} onChange={event => setMode(event.target.value as GeneratorSettings["mode"])}><option value="different">اسم وكلمة مرور مختلفان</option><option value="same">PIN متطابق</option><option value="username_only">اسم مستخدم فقط</option></select></label><label>طول الرمز<input type="number" min="3" max="30" value={length} onChange={event => setLength(event.target.value)} /></label><button>إنشاء وحفظ RSC</button></form><section className="panel"><h2>دفعاتك</h2>{batchState.loading ? <p>جارٍ التحميل…</p> : batchState.records.length ? <ul className="list">{batchState.records.map(record => <li key={record.id}><b>{String(record.name ?? "دفعة كروت")}</b><span>{String(record.status ?? "local")} · {String(record.count ?? 0)} كرت</span><small>{record.createdAt ? new Date(String(record.createdAt)).toLocaleString("ar") : ""}</small><div className="batch-actions"><button className="secondary" onClick={() => download(record)}>تنزيل RSC</button>{String(record.status) === "local" && <button className="secondary" onClick={() => void batchState.update(record.id, { ...record, status: "cancelled" }).then(() => onNotice("تم إلغاء الدفعة. لم يُرسل شيء إلى الراوتر."))}>إلغاء</button>}<button className="danger" onClick={() => { if (confirm("حذف هذه الدفعة؟")) void batchState.remove(record.id).then(() => onNotice("تم حذف الدفعة.")); }}>حذف</button></div></li>)}</ul> : <Empty text="لا توجد دفعات محفوظة في حسابك." />}</section></section></>;
}
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
